### ISSUE TITLE
seq_len = tf.shape(inputs).numpy()[0] 的问题

### ISSUE THREAD

**Issue by chaiwentao** [CNALeon007/TrajGRU#2]
你好，我想请问下trajGRU.py文件中的seq_len = tf.shape(inputs).numpy()[0]，这一句似乎会出错，报错的是：AttributeError: 'Tensor' object has no attribute 'numpy'，我也没有用过此语法，请问这个seq_len是什么序列？是否可以用其他来代替？ tf.shape(inputs).numpy()[1]又是什么？谢谢！

**Comment by CNALeon007** [comment]
你好，输入inputs的shape其实是(seq_len, batch_size, height, width, channel)，seq_len = tf.shape(inputs).numpy()[0]其实就是提取seq_len这一维度的长度，所有类似的表述都是提取维度长度的意思，tf.shape(inputs)很好理解，就是获取inputs的shape，返回的是tensor，tensor.numpy()这种表述貌似只在tf2.0里面才有，用于把tensor转换成numpy数组，所以这里会报错，tf1.14版本可以用inputs.shape.as_list()替换。
